[build]
  publish = "dist" # Adjust if your build output directory is different

# Handle the WASM files correctly
[[headers]]
  for = "*.wasm"
  [headers.values]
    Content-Type = "application/wasm"

# Add CORS headers for WASM execution
[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"